### ISSUE TITLE
WSI MPP

### ISSUE THREAD

**Issue by biototem** [YANRUI121/HDMIL#1]
Thanks a lot for sharing the FUSCC dataset. Can you kindly provide the mpp (pixel resolution) for the level 1 and level 2 images?

Btw, it is mentioned that FUSCC dataset has 103 mutation WSI and 16 wildtype WSI in the Dataset section, however the number of image for each class is opposite in the image folder (16 in mutation folder and 103 in wildtype folder). Can you confirm which is correct? Thanks!

**Comment by YANRUI121** [comment]
Apparent magnification: 40X
MPP: 0.25
For the number of images of each class, please refer to  README file.

**Comment by biototem** [comment]
Thanks!
