### ISSUE TITLE
Labels used in Table 3 of the paper

### ISSUE THREAD

**Issue by 464hee** [YANRUI121/HDMIL#2]
Thank you for your outstanding work, I have downloaded the relevant wsi data, but I am having some trouble with the labeling, can you provide the labels for the TCGA-Bladder used in the paper, just need the Case ID and the corresponding labels, thank you very much!

**Comment by YANRUI121** [comment]
Did you send me an email? I have emailed the file to you.

**Comment by 464hee** [comment]
Yes, I have received the attachment, thanks
